import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import HeroBanner from '../components/HeroBanner'
import AboutBanner from "../components/AboutBanner";
import Services from "../components/Services";
import Contact from "../components/Contact";
import FooterBanner from "../components/FooterBanner";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const linkData = [
    {
      title: "About",
      links: [{ label: "About BIMZHUA", link: "/" }],
    },
    {
      title: "Contact Us",
      links: [{ label: "Contact us via mail", link: "/contact" }],
    },
    {
      title: "Community",
      links: [
        { label: "Follow on Twitter", link: "/" },
        { label: "Follow on Instagram", link: "/" },
      ],
    },
  ];

  return (
    <>
      <Head>
        <title>BIMZHUA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <HeroBanner />
        <AboutBanner />
        <Services />
        <Contact />
        <FooterBanner data={linkData} />
      </>
    </>
  );
}
